//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nam
    {
        public Nam()
        {
            this.DSPhimBoes = new HashSet<DSPhimBo>();
            this.DSPhimLes = new HashSet<DSPhimLe>();
        }
    
        public int MaNam { get; set; }
        public Nullable<int> TenNam { get; set; }
    
        public virtual ICollection<DSPhimBo> DSPhimBoes { get; set; }
        public virtual ICollection<DSPhimLe> DSPhimLes { get; set; }
    }
}
