//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.DSPhimBoes = new HashSet<DSPhimBo>();
            this.DSPhimBoes1 = new HashSet<DSPhimBo>();
        }
    
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> Quyen { get; set; }
    
        public virtual ICollection<DSPhimBo> DSPhimBoes { get; set; }
        public virtual ICollection<DSPhimBo> DSPhimBoes1 { get; set; }
    }
}
