//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoai
    {
        public TheLoai()
        {
            this.DSPhimBoes = new HashSet<DSPhimBo>();
            this.DSPhimLes = new HashSet<DSPhimLe>();
        }
    
        public int IDTheLoai { get; set; }
        public string TenTheLoai { get; set; }
    
        public virtual ICollection<DSPhimBo> DSPhimBoes { get; set; }
        public virtual ICollection<DSPhimLe> DSPhimLes { get; set; }
    }
}
